In [1]:
import champ_placement as chp

In [2]:
#initialise the class
show = chp.champ_placement()

height ='Lge'

#get the top 20 by calling index 0
show.overall_results(height)[0]

Most recent show (2024-04-14 00:00:00) was 'scottish border collie' but it was cancelled.
Last show to run was scunthorpe
Matching rows found:
Scunthorpe Championship Agility Show
Full final
Common Pairings with Points (Lowest to Highest):

C:\Users\rorti\OneDrive\Documents\coding\agility code\champ placment code\Attempt_2_2024\champ_placement.py:378: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_top_20['place'] = np.arange(1,len(df_top_20)+1)

                              Pairing  Points
place
1            (David Munnings, Legacy)       6
2              (Karen Marriott, Trio)      18
3                (Karl Benson, Tulip)      19
4               (Martin Reid, Snooze)      23
5                (Martin Reid, Shape)      24
6          (Chris Kerton, Copernicus)      26
7      (Mirella Ballestracci, Gibson)      27
8             (Michelle Waugh, Alvin)      29
9               (Naarah Cuddy, Lemon)      35
10            (Joanne Tristram, Fade)      36
11             (Lynne Gressler, Kite)      36
12              (Sioban Speedie, Sky)      38
13          (Nicola Wildman, Panache)      41
14               (Alan Gardner, Jess)      41
15                (Mike Bendell, Spy)      43
16                (Jo Gleed, Stealie)      44
17       (Connie Sellers-Lane, Fleur)      46
18              (Jenny Kimber, Rogue)      49
19             (Mike Bendell, Falcon)      53
20               (Lisa Miller, Tilly)      61

In [3]:
#get the overall non E by calling index 1
show.overall_results(height)[1]

Full final
Common Pairings with Points (Lowest to Highest):

C:\Users\rorti\OneDrive\Documents\coding\agility code\champ placment code\Attempt_2_2024\champ_placement.py:378: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_top_20['place'] = np.arange(1,len(df_top_20)+1)

                              Pairing  Points
place
1            (David Munnings, Legacy)       6
2              (Karen Marriott, Trio)      18
3                (Karl Benson, Tulip)      19
4               (Martin Reid, Snooze)      23
5                (Martin Reid, Shape)      24
6          (Chris Kerton, Copernicus)      26
7      (Mirella Ballestracci, Gibson)      27
8             (Michelle Waugh, Alvin)      29
9               (Naarah Cuddy, Lemon)      35
10            (Joanne Tristram, Fade)      36
11             (Lynne Gressler, Kite)      36
12              (Sioban Speedie, Sky)      38
13          (Nicola Wildman, Panache)      41
14               (Alan Gardner, Jess)      41
15                (Mike Bendell, Spy)      43
16                (Jo Gleed, Stealie)      44
17       (Connie Sellers-Lane, Fleur)      46
18              (Jenny Kimber, Rogue)      49
19             (Mike Bendell, Falcon)      53
20               (Lisa Miller, Tilly)      61
21                 (Nia Rose, Farlie)      63
22               (Sarah Webb, Silver)      68